spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: abc123
    username: root
    url: jdbc:mysql://localhost:3306/commom?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
